"""Tests for theme export."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from juce_theme_studio.core.assets import import_asset
from juce_theme_studio.core.controls import create_control
from juce_theme_studio.core.manifest import Screen, ThemeManifest
from juce_theme_studio.core.project import load_project, save_project
from juce_theme_studio.core.sprites import SpriteConfig
from juce_theme_studio.core.types import ControlType
from juce_theme_studio.juce.exporter import export_theme


def _project_with_knob(fixture_project: Path):
    loaded = load_project(fixture_project)
    manifest = loaded.manifest

    entry = import_asset(
        manifest, fixture_project,
        fixture_project / "Resources" / "knob_strip.png",
        is_sprite_sheet=True,
    )
    screen = manifest.screens[0] if manifest.screens else Screen(
        id="manual", name="Main", canvas_width=800, canvas_height=600,
    )
    if screen not in manifest.screens:
        manifest.screens.append(screen)

    sprite = SpriteConfig(frame_count=8, frame_width=64, frame_height=64)
    control = create_control(
        ControlType.KNOB, "Gain", 100, 200, 64, 64, entry.id, sprite,
    )
    control.mapping.cpp_variable = "gainSlider"
    control.mapping.parameter_id = "gain"
    control.preview_value = 0.5
    screen.controls.append(control)

    save_project(loaded)
    return loaded, manifest, entry


def test_export_generates_files(fixture_project: Path) -> None:
    _, manifest, _ = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    assert result.export_dir.is_dir()
    assert (result.export_dir / "ThemeLayout.json").is_file()
    assert (result.export_dir / "ThemeAssets.h").is_file()
    assert (result.export_dir / "GeneratedThemeComponents.cpp").is_file()
    assert (result.export_dir / "README-INTEGRATION.md").is_file()
    assert "// GENERATED BY JUCE Theme Studio" in (result.export_dir / "ThemeAssets.h").read_text()


def test_layout_json_carries_asset_and_state(fixture_project: Path) -> None:
    _, manifest, entry = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    layout = json.loads((result.export_dir / "ThemeLayout.json").read_text())
    assert "colors" in layout and layout["colors"]
    controls = [c for s in layout["screens"] for c in s["controls"]]
    control = next(c for c in controls if c["name"] == "Gain")
    # The exported filename must exist under assets/ so the C++ runtime can load it.
    assert control["asset_file"]
    assert (result.export_dir / "assets" / control["asset_file"]).is_file()
    assert control["value"] == 0.5
    assert control["sprite_config"]["frame_count"] == 8


def test_generated_cpp_is_functional_not_stub(fixture_project: Path) -> None:
    """Guard against regressing the generated C++ back to empty skeletons."""
    _, manifest, _ = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    assets_cpp = (result.export_dir / "ThemeAssets.cpp").read_text()
    laf_cpp = (result.export_dir / "ThemeLookAndFeel.cpp").read_text()
    comp_cpp = (result.export_dir / "GeneratedThemeComponents.cpp").read_text()

    # Images are really loaded and frames really sliced.
    assert "juce::JSON::parse" in assets_cpp
    assert "juce::ImageFileFormat::loadFrom" in assets_cpp
    assert "getClippedImage" in assets_cpp

    # The LookAndFeel actually draws sprite frames.
    assert "knobStrip.frame" in laf_cpp
    assert "g.drawImage" in laf_cpp

    # The screen component renders + the layout applier positions real children.
    assert "g.drawImage" in comp_cpp
    assert "findChildWithID" in comp_cpp

    # No empty-stub leftovers.
    combined = assets_cpp + laf_cpp + comp_cpp
    assert "// Draw sprite" not in combined
    assert "juce::ignoreUnused" not in combined


def test_export_rejects_output_subdir_escape_even_when_forced(fixture_project: Path) -> None:
    manifest = ThemeManifest(screens=[Screen(id="s1", name="Main")])
    manifest.export_settings.output_subdir = "../outside"

    with pytest.raises(ValueError, match="output subdir"):
        export_theme(manifest, fixture_project, force=True)

    assert not (fixture_project / "outside" / "ThemeLayout.json").exists()


def test_repeated_export_creates_unique_backups(fixture_project: Path) -> None:
    manifest = ThemeManifest(screens=[Screen(id="s1", name="Main")])
    first = export_theme(manifest, fixture_project)
    (first.export_dir / "marker.txt").write_text("old", encoding="utf-8")

    second = export_theme(manifest, fixture_project)
    third = export_theme(manifest, fixture_project)

    assert second.backup_dir is not None
    assert third.backup_dir is not None
    assert second.backup_dir != third.backup_dir


def test_generated_cpp_screen_layout_identifiers_are_valid_and_unique(
    fixture_project: Path,
) -> None:
    manifest = ThemeManifest(
        screens=[
            Screen(id="a1", name="123 Main"),
            Screen(id="b2", name="Main-Page"),
            Screen(id="c3", name="Main Page"),
        ]
    )

    result = export_theme(manifest, fixture_project)
    header = (result.export_dir / "GeneratedThemeComponents.h").read_text()

    assert "struct Screen_123_MainLayout" in header
    assert "struct Main_PageLayout" in header
    assert "struct Main_Page_2Layout" in header
    assert "struct 123_MainLayout" not in header


def test_export_can_write_to_explicit_staging_directory(fixture_project: Path) -> None:
    _, manifest, _ = _project_with_knob(fixture_project)
    staging = fixture_project / ".juce_theme_studio" / "applies" / "preview" / "generated"

    from juce_theme_studio.juce.exporter import export_theme_to_directory

    result = export_theme_to_directory(manifest, fixture_project, staging)

    assert result.export_dir == staging
    assert (staging / "ThemeLayout.json").is_file()
    assert (staging / "ThemeAssets.cpp").is_file()
    assert (staging / "GeneratedThemeComponents.h").is_file()
    assert (staging / "assets").is_dir()
    assert any(path.endswith("ThemeLayout.json") for path in result.files_written)
    assert result.backup_dir is None


def test_explicit_staging_directory_ignores_manual_output_subdir(
    fixture_project: Path,
) -> None:
    _, manifest, _ = _project_with_knob(fixture_project)
    manifest.export_settings.output_subdir = "../outside"
    staging = fixture_project / ".juce_theme_studio" / "applies" / "safe" / "generated"

    from juce_theme_studio.juce.exporter import export_theme_to_directory

    result = export_theme_to_directory(manifest, fixture_project, staging)

    assert result.validation is not None
    assert not result.validation.has_blocking_errors
    assert result.export_dir == staging
    assert result.backup_dir is None
    assert (staging / "ThemeLayout.json").is_file()
    assert manifest.export_settings.output_subdir == "../outside"


def test_explicit_staging_directory_must_stay_inside_project_root(
    fixture_project: Path,
    tmp_path: Path,
) -> None:
    _, manifest, _ = _project_with_knob(fixture_project)

    from juce_theme_studio.juce.exporter import export_theme_to_directory

    with pytest.raises(ValueError, match="export directory"):
        export_theme_to_directory(manifest, fixture_project, tmp_path / "outside")
