"""Tests for theme export."""

from __future__ import annotations

import json
from pathlib import Path

from juce_theme_studio.core.assets import import_asset
from juce_theme_studio.core.controls import create_control
from juce_theme_studio.core.manifest import Screen
from juce_theme_studio.core.project import load_project, save_project
from juce_theme_studio.core.sprites import SpriteConfig
from juce_theme_studio.core.types import ControlType
from juce_theme_studio.juce.exporter import export_theme


def _project_with_knob(fixture_project: Path):
    loaded = load_project(fixture_project)
    manifest = loaded.manifest

    entry = import_asset(
        manifest, fixture_project,
        fixture_project / "Resources" / "knob_strip.png",
        is_sprite_sheet=True,
    )
    screen = manifest.screens[0] if manifest.screens else Screen(
        id="manual", name="Main", canvas_width=800, canvas_height=600,
    )
    if screen not in manifest.screens:
        manifest.screens.append(screen)

    sprite = SpriteConfig(frame_count=8, frame_width=64, frame_height=64)
    control = create_control(
        ControlType.KNOB, "Gain", 100, 200, 64, 64, entry.id, sprite,
    )
    control.mapping.cpp_variable = "gainSlider"
    control.mapping.parameter_id = "gain"
    control.preview_value = 0.5
    screen.controls.append(control)

    save_project(loaded)
    return loaded, manifest, entry


def test_export_generates_files(fixture_project: Path) -> None:
    _, manifest, _ = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    assert result.export_dir.is_dir()
    assert (result.export_dir / "ThemeLayout.json").is_file()
    assert (result.export_dir / "ThemeAssets.h").is_file()
    assert (result.export_dir / "GeneratedThemeComponents.cpp").is_file()
    assert (result.export_dir / "README-INTEGRATION.md").is_file()
    assert "// GENERATED BY JUCE Theme Studio" in (result.export_dir / "ThemeAssets.h").read_text()


def test_layout_json_carries_asset_and_state(fixture_project: Path) -> None:
    _, manifest, entry = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    layout = json.loads((result.export_dir / "ThemeLayout.json").read_text())
    assert "colors" in layout and layout["colors"]
    controls = [c for s in layout["screens"] for c in s["controls"]]
    control = next(c for c in controls if c["name"] == "Gain")
    # The exported filename must exist under assets/ so the C++ runtime can load it.
    assert control["asset_file"]
    assert (result.export_dir / "assets" / control["asset_file"]).is_file()
    assert control["value"] == 0.5
    assert control["sprite_config"]["frame_count"] == 8


def test_generated_cpp_is_functional_not_stub(fixture_project: Path) -> None:
    """Guard against regressing the generated C++ back to empty skeletons."""
    _, manifest, _ = _project_with_knob(fixture_project)
    result = export_theme(manifest, fixture_project)

    assets_cpp = (result.export_dir / "ThemeAssets.cpp").read_text()
    laf_cpp = (result.export_dir / "ThemeLookAndFeel.cpp").read_text()
    comp_cpp = (result.export_dir / "GeneratedThemeComponents.cpp").read_text()

    # Images are really loaded and frames really sliced.
    assert "juce::JSON::parse" in assets_cpp
    assert "juce::ImageFileFormat::loadFrom" in assets_cpp
    assert "getClippedImage" in assets_cpp

    # The LookAndFeel actually draws sprite frames.
    assert "knobStrip.frame" in laf_cpp
    assert "g.drawImage" in laf_cpp

    # The screen component renders + the layout applier positions real children.
    assert "g.drawImage" in comp_cpp
    assert "findChildWithID" in comp_cpp

    # No empty-stub leftovers.
    combined = assets_cpp + laf_cpp + comp_cpp
    assert "// Draw sprite" not in combined
    assert "juce::ignoreUnused" not in combined
