"""Tests for theme export."""

from __future__ import annotations

from pathlib import Path

from juce_theme_studio.core.assets import import_asset
from juce_theme_studio.core.controls import create_control
from juce_theme_studio.core.manifest import Screen
from juce_theme_studio.core.project import load_project, save_project
from juce_theme_studio.core.sprites import SpriteConfig
from juce_theme_studio.core.types import ControlType
from juce_theme_studio.juce.exporter import export_theme


def test_export_generates_files(fixture_project: Path) -> None:
    loaded = load_project(fixture_project)
    manifest = loaded.manifest

    entry = import_asset(
        manifest, fixture_project,
        fixture_project / "Resources" / "knob_strip.png",
        is_sprite_sheet=True,
    )
    screen = manifest.screens[0] if manifest.screens else Screen(
        id="manual", name="Main", canvas_width=800, canvas_height=600,
    )
    if screen not in manifest.screens:
        manifest.screens.append(screen)

    sprite = SpriteConfig(frame_count=8, frame_width=64, frame_height=64)
    control = create_control(
        ControlType.KNOB, "Gain", 100, 200, 64, 64, entry.id, sprite,
    )
    control.mapping.cpp_variable = "gainSlider"
    control.mapping.parameter_id = "gain"
    screen.controls.append(control)

    save_project(loaded)
    result = export_theme(manifest, fixture_project)

    assert result.export_dir.is_dir()
    assert (result.export_dir / "ThemeLayout.json").is_file()
    assert (result.export_dir / "ThemeAssets.h").is_file()
    assert (result.export_dir / "GeneratedThemeComponents.cpp").is_file()
    assert "// GENERATED BY JUCE Theme Studio" in (result.export_dir / "ThemeAssets.h").read_text()
