"""Theme export: JSON layout and generated JUCE C++ helpers."""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from juce_theme_studio.core.assets import resolve_asset_path
from juce_theme_studio.core.manifest import ThemeManifest
from juce_theme_studio.core.types import STUDIO_DIR
from juce_theme_studio.core.validation import ValidationReport, validate_manifest

GENERATED_BANNER = "// GENERATED BY JUCE Theme Studio — DO NOT EDIT MANUALLY\n"


@dataclass
class ExportResult:
    export_dir: Path
    files_written: list[str] = field(default_factory=list)
    validation: ValidationReport | None = None
    backup_dir: Path | None = None


def preview_export_files(manifest: ThemeManifest, project_root: Path) -> list[str]:
    """List relative paths that export would write (for preview dialog)."""
    project_root = project_root.resolve()
    studio = project_root / STUDIO_DIR
    export_dir = studio / manifest.export_settings.output_subdir
    rel_export = str(export_dir.relative_to(project_root))
    files: list[str] = []

    if manifest.export_settings.export_json:
        files.append(f"{rel_export}/ThemeLayout.json")

    if manifest.export_settings.copy_assets:
        for asset in manifest.assets:
            name = Path(asset.relative_path).name
            files.append(f"{rel_export}/assets/{name}")

    if manifest.export_settings.export_cpp:
        for name in (
            "ThemeAssets.h",
            "ThemeAssets.cpp",
            "ThemeLookAndFeel.h",
            "ThemeLookAndFeel.cpp",
            "GeneratedThemeComponents.h",
            "GeneratedThemeComponents.cpp",
        ):
            files.append(f"{rel_export}/{name}")

    return files


def export_theme(
    manifest: ThemeManifest,
    project_root: Path,
    *,
    force: bool = False,
) -> ExportResult:
    """Export theme to .juce_theme_studio/exports/ with backup."""
    project_root = project_root.resolve()
    validation = validate_manifest(manifest, project_root)
    if validation.has_blocking_errors and not force:
        studio = project_root / STUDIO_DIR
        return ExportResult(export_dir=studio / "exports", validation=validation)

    studio = project_root / STUDIO_DIR
    export_dir = studio / manifest.export_settings.output_subdir
    backup_dir = _create_backup(studio, export_dir)

    export_dir.mkdir(parents=True, exist_ok=True)
    assets_out = export_dir / "assets"
    assets_out.mkdir(exist_ok=True)

    result = ExportResult(export_dir=export_dir, validation=validation, backup_dir=backup_dir)
    settings = manifest.export_settings
    ns = settings.namespace

    if settings.export_json:
        layout_path = export_dir / "ThemeLayout.json"
        layout_data = _build_layout_json(manifest)
        layout_path.write_text(json.dumps(layout_data, indent=2) + "\n", encoding="utf-8")
        result.files_written.append(str(layout_path.relative_to(project_root)))

    if settings.copy_assets:
        for asset in manifest.assets:
            src = resolve_asset_path(project_root, asset)
            if src.is_file():
                dest = assets_out / Path(asset.relative_path).name
                shutil.copy2(src, dest)
                result.files_written.append(str(dest.relative_to(project_root)))

    if settings.export_cpp:
        cpp_files = {
            "ThemeAssets.h": _gen_theme_assets_h(ns),
            "ThemeAssets.cpp": _gen_theme_assets_cpp(ns),
            "ThemeLookAndFeel.h": _gen_lookandfeel_h(ns),
            "ThemeLookAndFeel.cpp": _gen_lookandfeel_cpp(ns),
            "GeneratedThemeComponents.h": _gen_components_h(ns, manifest),
            "GeneratedThemeComponents.cpp": _gen_components_cpp(ns, manifest),
        }
        for filename, content in cpp_files.items():
            path = export_dir / filename
            _write_cpp(path, content, project_root, result)

    return result


def _create_backup(studio_dir: Path, export_dir: Path) -> Path | None:
    if not export_dir.exists() or not any(export_dir.iterdir()):
        return None
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup = studio_dir / "backups" / f"export_{ts}"
    shutil.copytree(export_dir, backup)
    return backup


def _write_cpp(path: Path, content: str, project_root: Path, result: ExportResult) -> None:
    path.write_text(content, encoding="utf-8")
    result.files_written.append(str(path.relative_to(project_root)))


def _build_layout_json(manifest: ThemeManifest) -> dict:
    return {
        "schema_version": manifest.schema_version,
        "screens": [
            {
                "name": s.name,
                "juce_component": s.juce_component,
                "width": s.canvas_width,
                "height": s.canvas_height,
                "background_asset": s.background_asset_id,
                "controls": [
                    {
                        "name": c.name,
                        "type": c.control_type.value,
                        "bounds": {"x": c.x, "y": c.y, "width": c.width, "height": c.height},
                        "z_index": c.z_index,
                        "asset_id": c.asset_id,
                        "sprite_config": c.sprite_config.to_dict() if c.sprite_config else None,
                        "mapping": c.mapping.to_dict(),
                        "label_text": c.label_text,
                    }
                    for c in sorted(s.controls, key=lambda x: x.z_index)
                ],
            }
            for s in manifest.screens
        ],
    }


def _gen_theme_assets_h(ns: str) -> str:
    return f"""{GENERATED_BANNER}
#pragma once

#include <JuceHeader.h>

namespace {ns}
{{
class ThemeAssets
{{
public:
    static juce::Image getImage (const juce::String& assetId);
    static juce::Image getSpriteFrame (const juce::String& assetId, int frameIndex,
                                       int frameW, int frameH, int sheetW);
    static bool loadFromLayout (const juce::File& layoutJson);
}};
}}
"""


def _gen_theme_assets_cpp(ns: str) -> str:
    return f"""{GENERATED_BANNER}
#include "ThemeAssets.h"

namespace {ns}
{{
static std::map<juce::String, juce::Image> g_themeImages;

juce::Image ThemeAssets::getImage (const juce::String& assetId)
{{
    auto it = g_themeImages.find (assetId);
    return it != g_themeImages.end() ? it->second : juce::Image();
}}

juce::Image ThemeAssets::getSpriteFrame (const juce::String& assetId, int frameIndex,
                                         int frameW, int frameH, int sheetW)
{{
    auto sheet = getImage (assetId);
    if (! sheet.isValid())
        return {{}};

    const int x = (frameIndex * frameW) % sheetW;
    const int y = (frameIndex * frameW) / sheetW * frameH;
    return sheet.getClippedImage ({{ x, y, frameW, frameH }});
}}

bool ThemeAssets::loadFromLayout (const juce::File& layoutJson)
{{
    // Load asset paths from ThemeLayout.json and populate g_themeImages.
    juce::ignoreUnused (layoutJson);
    return true;
}}
}}
"""


def _gen_lookandfeel_h(ns: str) -> str:
    return f"""{GENERATED_BANNER}
#pragma once

#include <JuceHeader.h>
#include "ThemeAssets.h"

namespace {ns}
{{
class ThemeLookAndFeel : public juce::LookAndFeel_V4
{{
public:
    void drawRotarySlider (juce::Graphics& g, int x, int y, int width, int height,
                           float sliderPos, float rotaryStartAngle, float rotaryEndAngle,
                           juce::Slider& slider) override;
    void drawButtonBackground (juce::Graphics& g, juce::Button& button,
                               const juce::Colour& backgroundColour,
                               bool shouldDrawButtonAsHighlighted,
                               bool shouldDrawButtonAsDown) override;
}};
}}
"""


def _gen_lookandfeel_cpp(ns: str) -> str:
    return f"""{GENERATED_BANNER}
#include "ThemeLookAndFeel.h"

namespace {ns}
{{
void ThemeLookAndFeel::drawRotarySlider (juce::Graphics& g, int x, int y, int width, int height,
                                         float sliderPos, float rotaryStartAngle,
                                         float rotaryEndAngle, juce::Slider& slider)
{{
    juce::ignoreUnused (g, x, y, width, height, sliderPos,
                        rotaryStartAngle, rotaryEndAngle, slider);
    // Draw sprite knob frame based on sliderPos and ThemeAssets.
}}

void ThemeLookAndFeel::drawButtonBackground (juce::Graphics& g, juce::Button& button,
                                             const juce::Colour& backgroundColour,
                                             bool shouldDrawButtonAsHighlighted,
                                             bool shouldDrawButtonAsDown)
{{
    juce::ignoreUnused (g, button, backgroundColour,
                        shouldDrawButtonAsHighlighted, shouldDrawButtonAsDown);
    // Draw sprite button state from ThemeAssets.
}}
}}
"""


def _gen_components_h(ns: str, manifest: ThemeManifest) -> str:
    lines = [
        GENERATED_BANNER,
        "#pragma once",
        "",
        "#include <JuceHeader.h>",
        "#include \"ThemeAssets.h\"",
        "",
        f"namespace {ns}",
        "{",
        "/** Apply exported bounds to a component tree. */",
        "void applyScreenLayout (juce::Component& root, const juce::String& screenName);",
        "",
    ]
    for screen in manifest.screens:
        safe = _safe_cpp(screen.juce_component or screen.name)
        lines.append(f"// Screen: {screen.name} ({screen.canvas_width}x{screen.canvas_height})")
        lines.append(f"struct {safe}Layout {{ static void apply (juce::Component& root); }};")
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _gen_components_cpp(ns: str, manifest: ThemeManifest) -> str:
    lines = [
        GENERATED_BANNER,
        '#include "GeneratedThemeComponents.h"',
        "",
        f"namespace {ns}",
        "{",
    ]
    for screen in manifest.screens:
        safe = _safe_cpp(screen.juce_component or screen.name)
        lines.append(f"void {safe}Layout::apply (juce::Component& root)")
        lines.append("{")
        for c in screen.controls:
            var = c.mapping.cpp_variable or c.name
            lines.append(
                f"    // {c.control_type.value}: {c.name} "
                f"setBounds({c.x}, {c.y}, {c.width}, {c.height});"
            )
            lines.append(
                f"    if (auto* comp = root.findChildWithID (\"{var}\"))"
            )
            lines.append(
                f"        comp->setBounds ({c.x}, {c.y}, {c.width}, {c.height});"
            )
        lines.append("}")
        lines.append("")
    lines.append("void applyScreenLayout (juce::Component& root, const juce::String& screenName)")
    lines.append("{")
    lines.append("    juce::ignoreUnused (root, screenName);")
    lines.append("    // Dispatch to screen-specific layout helpers.")
    lines.append("}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _safe_cpp(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name) or "Screen"
